name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  ASSIGNEE_ID: ${{ secrets.ASSIGNEE_ID }}
  ISSUE_TYPE: ${{ secrets.ISSUE_TYPE }}
  JIRA_ATTACH_ISSUE_URL: ${{ secrets.JIRA_ATTACH_ISSUE_URL }}
  JIRA_CREATE_ISSUE_URL: ${{ secrets.JIRA_CREATE_ISSUE_URL }}
  JIRA_DEFAULT_HEADERS: ${{ secrets.JIRA_DEFAULT_HEADERS }}
  JIRA_DEFAULT_HEADERS_ATTACHMENTS: ${{ secrets.JIRA_DEFAULT_HEADERS_ATTACHMENTS }}
  PROJECT_KEY: ${{ secrets.PROJECT_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Get packages
        run: flutter pub get

      - name: Set Environment Variables
        run: |
          echo "ASSIGNEE_ID=$ASSIGNEE_ID" >> $GITHUB_ENV
          echo "ISSUE_TYPE=$ISSUE_TYPE" >> $GITHUB_ENV
          echo "JIRA_ATTACH_ISSUE_URL=$JIRA_ATTACH_ISSUE_URL" >> $GITHUB_ENV
          echo "JIRA_CREATE_ISSUE_URL=$JIRA_CREATE_ISSUE_URL" >> $GITHUB_ENV
          echo "JIRA_DEFAULT_HEADERS=$JIRA_DEFAULT_HEADERS" >> $GITHUB_ENV
          echo "JIRA_DEFAULT_HEADERS_ATTACHMENTS=$JIRA_DEFAULT_HEADERS_ATTACHMENTS" >> $GITHUB_ENV
          echo "PROJECT_KEY=$PROJECT_KEY" >> $GITHUB_ENV

      - name: Build Web App
        run: flutter build web --release

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
