name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ASSIGNEE_ID: ${{ secrets.ASSIGNEE_ID }}
      ISSUE_TYPE: ${{ secrets.ISSUE_TYPE }}
      JIRA_ATTACH_ISSUE_URL: ${{ secrets.JIRA_ATTACH_ISSUE_URL }}
      JIRA_CREATE_ISSUE_URL: ${{ secrets.JIRA_CREATE_ISSUE_URL }}
      JIRA_DEFAULT_HEADERS: ${{ secrets.JIRA_DEFAULT_HEADERS }}
      JIRA_DEFAULT_HEADERS_ATTACHMENTS: ${{ secrets.JIRA_DEFAULT_HEADERS_ATTACHMENTS }}
      PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '19'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.18.6'
      - name: Install dependencies
        run: flutter pub get
      - name: Build web
        run: flutter build web --release
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web/
