name: deployments
on:
  push:
    branches: [main]

jobs:
  deployProd:
    name: 'Deploy to production environment'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '12.x'
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_ASSIGNEE_ID: ${{ secrets.ASSIGNEE_ID }}
          envkey_ISSUE_TYPE: ${{ secrets.ISSUE_TYPE }}
          envkey_JIRA_ATTACH_ISSUE_URL: ${{ secrets.JIRA_ATTACH_ISSUE_URL }}
          envkey_JIRA_CREATE_ISSUE_URL: ${{ secrets.JIRA_CREATE_ISSUE_URL }}
          envkey_JIRA_DEFAULT_HEADERS: ${{ secrets.JIRA_DEFAULT_HEADERS }}
          envkey_JIRA_DEFAULT_HEADERS_ATTACHMENTS: ${{ secrets.JIRA_DEFAULT_HEADERS_ATTACHMENTS }}
          envkey_PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.18.6'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web --release --incremental
      - uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/web
