name: deployments
on:
  push:
    branches: [main]

jobs:
  deployProd:
    name: 'Deploy to production environment'
    if: github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: SpicyPizza/create-envfile@v1
        with:
          envkey_ASSIGNEE_ID: ${{ secrets.ASSIGNEE_ID }}
          envkey_ISSUE_TYPE: ${{ secrets.ISSUE_TYPE }}
          envkey_JIRA_ATTACH_ISSUE_URL: ${{ secrets.JIRA_ATTACH_ISSUE_URL }}
          envkey_JIRA_CREATE_ISSUE_URL: ${{ secrets.JIRA_CREATE_ISSUE_URL }}
          envkey_JIRA_DEFAULT_HEADERS: ${{ secrets.JIRA_DEFAULT_HEADERS }}
          envkey_JIRA_DEFAULT_HEADERS_ATTACHMENTS: ${{ secrets.JIRA_DEFAULT_HEADERS_ATTACHMENTS }}
          envkey_PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm install -g firebase-tools
      - run: firebase login --no-localhost --ci
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.18.6'
          node-version: '16.x'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build web --release --incremental
      - uses: firebase/github-actions/deploy@v0.5.0
        with:
          args: '--only hosting'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
